exclude:
- /js/lib/.*
component_depth: 1
languages:
- name: python
  production:
    include:
      - /python/*
    exclude:
      - /python/gilded_rose/updater/legacy.py
      - /python/texttest_fixture.py
