# Makefile
.PHONY = help

help:
	@echo "---------------HELP-----------------"
	@echo "To compile the requirements run: make compile"
	@echo "------------------------------------"

compile:
	pip-compile dev-requirements.in
	pip-compile requirements.in
